### ISSUE TITLE
biggles setup fails on current OSX

### ISSUE THREAD

**Issue by graik** [biggles-plot/biggles#138]
The setup instructions for OSX are now out of date. homebrew has been modified and the ```brew install plotutils``` does not any longer accept the ```--with-x11``` option. Possibly because of this, my biggles installation stopped working and also re-installation of plotutils or biggles doesn't seem to fix it:
```
pip install biggles
python
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import biggles
>>> import numpy
>>> x = numpy.arange(0,10,0.3)
>>> p = biggles.FramedPlot()
>>> p.add( biggles.Curve(x, numpy.cos(x)) )
>>> p.show()
libplot: ignoring request to create plotter of unknown type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/biggles/biggles.py", line 2527, in show
    self.show_x11(width, height)
  File "/usr/local/lib/python3.7/site-packages/biggles/biggles.py", line 2550, in show_x11
    with ScreenRenderer(persistent, width, height) as device:
  File "/usr/local/lib/python3.7/site-packages/biggles/libplot/renderer.py", line 491, in ScreenRenderer
    return NonInteractiveScreenRenderer(width, height)
  File "/usr/local/lib/python3.7/site-packages/biggles/libplot/renderer.py", line 439, in __init__
    parameters)
  File "/usr/local/lib/python3.7/site-packages/biggles/libplot/renderer.py", line 152, in __init__
    super(LibplotRenderer, self).__init__(type, parameters, filename)
RuntimeError: could not create plotter
>>> 
```
Any ideas how to fix this? Forcing recompilation didn't fix the issue either (```pip install --no-binary :all: biggles```)

Thanks

**Comment by JuanaHe** [comment]
Have you solved this question? I face the same challenge.

**Comment by graik** [comment]
I didn't get it to work, no.

**Comment by esheldon** [comment]
I don't have a mac for testing, maybe another maintainer can have a look

**Comment by graik** [comment]
This issue still persists. However, partial workaround:

(1) `git clone https://github.com/biggles-plot/biggles.git`
(2) Edit setup.py ... comment out `use_2to3=True,`
(3) `pip install .`

The installation succeeds but import fails because of a missing geometry package (next issue).
